server:
  port: ${GPC_SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/patient_switching
    username: gpc_user
    password: ${GPC_USER_DB_PASSWORD:pass}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings
