server:
  port: ${GPC_FACADE_SERVER_PORT:8080}

spring:
  datasource:
    url: ${PSS_DB_URL:jdbc:postgresql://localhost:5436/patient_switching}
    username: gpc_user
    password: ${GPC_FACADE_USER_DB_PASSWORD}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

amqp:
  pss:
    queueName: ${PSS_QUEUE_NAME:pssQueue}
    broker: ${PSS_AMQP_BROKER:amqp://localhost:5672}
    username: ${PSS_AMQP_USERNAME:}
    password: ${PSS_AMQP_PASSWORD:}
    maxRedeliveries: ${PSS_AMQP_MAX_REDELIVERIES:3}
