server:
  port: ${GPC_SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/pss
    username: pss
    password:
  liquibase:
    default-schema: public

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings
