server:
  port: ${GPC_FACADE_SERVER_PORT:8081}

spring:
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5436/patient_switching}
    username: gpc_user
    password: ${GPC_FACADE_USER_DB_PASSWORD}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

amqp:
  pss:
    queueName: ${PS_QUEUE_NAME:pssQueue}
    broker: ${PS_AMQP_BROKER:amqp://localhost:5672}
    username: ${PS_AMQP_USERNAME:}
    password: ${PS_AMQP_PASSWORD:}
    maxRedeliveries: ${PS_AMQP_MAX_REDELIVERIES:3}
