version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directories:
      - "/common"
      - "/db-connector"
      - "/gp2gp-translator"
      - "/gpc-api-facade"
      - "/schema"
      - "/smoke-tests"
    schedule:
      interval: "weekly"
