server:
  port: ${GPC_SERVER_PORT:8080}

logging:
  level:
    com.nhs.adaptors.gpc: DEBUG

spring:
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5436/patient_switching}
    username: gpc_user
    password: ${GPC_USER_DB_PASSWORD}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
