version: '3'

############ Network ##############

networks:
  nia-ps:
    external: true

services:

  ############### MHS specific   ###################

  inbound:
    image: nhsdev/nia-mhs-inbound:1.2.4-amd64
    networks:
      - nia-ps
    ports:
      - "${MHS_INBOUND_PORT}:443"
      - "8079:80"
      - "${MHS_INBOUND_HEALTHCHECK_SERVER_PORT}:${MHS_INBOUND_HEALTHCHECK_SERVER_PORT}"
    environment:
      - MHS_INBOUND_HEALTHCHECK_SERVER_PORT
      - MHS_LOG_LEVEL
      - MHS_SECRET_PARTY_KEY
      - MHS_SECRET_CLIENT_CERT
      - MHS_SECRET_CLIENT_KEY
      - MHS_SECRET_CA_CERTS
      - MHS_INBOUND_QUEUE_BROKERS=${MHS_AMQP_BROKER}
      - MHS_INBOUND_QUEUE_NAME=${MHS_QUEUE_NAME}
      - MHS_SECRET_INBOUND_QUEUE_USERNAME=${MHS_AMQP_USERNAME}
      - MHS_SECRET_INBOUND_QUEUE_PASSWORD=${MHS_AMQP_PASSWORD}
      - MHS_STATE_TABLE_NAME
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME
      - MHS_DB_ENDPOINT_URL
      - MHS_INBOUND_QUEUE_MESSAGE_TTL_IN_SECONDS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MHS_INBOUND_USE_SSL
      - TCP_PORTS=${MHS_INBOUND_PORT}
      - SERVICE_PORTS=${MHS_INBOUND_SERVICE_PORTS}

  outbound:
    image: nhsdev/nia-mhs-outbound:1.2.4-amd64
    networks:
      - nia-ps
    ports:
      - "${MHS_OUTBOUND_PORT}:80"
    environment:
      - MHS_LOG_LEVEL
      - MHS_SECRET_PARTY_KEY
      - MHS_SECRET_CLIENT_CERT
      - MHS_SECRET_CLIENT_KEY
      - MHS_SECRET_CA_CERTS
      - MHS_STATE_TABLE_NAME
      - MHS_DB_ENDPOINT_URL
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MHS_RESYNC_INTERVAL
      - MAX_RESYNC_RETRIES
      - MHS_SPINE_ROUTE_LOOKUP_URL
      - MHS_SPINE_ORG_CODE
      - MHS_SPINE_REQUEST_MAX_SIZE
      - MHS_FORWARD_RELIABLE_ENDPOINT_URL
      - MHS_OUTBOUND_VALIDATE_CERTIFICATE
      - SERVICE_PORTS
      - MHS_OUTBOUND_ROUTING_LOOKUP_METHOD
      - MHS_SDS_API_URL
      - MHS_SDS_API_KEY

  #  route:
  #    image: nhsdev/nia-mhs-route:1.2.2
  #    networks:
  #      - nia-ps
  #    ports:
  #      - "${MHS_ROUTE_PORT}:80"
  #    environment:
  #      - MHS_LOG_LEVEL
  #      - MHS_SDS_URL
  #      - MHS_SDS_SEARCH_BASE
  #      - MHS_DISABLE_SDS_TLS
  #      - MHS_SDS_REDIS_CACHE_HOST=${MHS_SDS_REDIS_CACHE_HOST_NAME}
  #      - MHS_SDS_REDIS_DISABLE_TLS

  ########### PS Adapter Specific ###############

  gpc_facade:
    image: nhsdev/nia-ps-facade:0.3-amd64
    ports:
      - "8081:8081"
    depends_on:
      - ps_db
    environment:
      - GPC_FACADE_SERVER_PORT
      - PS_DB_URL
      - GPC_FACADE_USER_DB_PASSWORD
      - PS_AMQP_BROKER
      - PS_QUEUE_NAME
      - PS_AMQP_USERNAME
      - PS_AMQP_PASSWORD
      - PS_AMQP_MAX_REDELIVERIES
      - PS_LOGGING_LEVEL
    networks:
      - nia-ps

  ps_gp2gp_translator:
    image: nhsdev/nia-ps-adaptor:0.4-amd64
    ports:
      - "8085:8085"
    depends_on:
      - ps_db
    environment:
      - GP2GP_TRANSLATOR_SERVER_PORT
      - PS_DB_URL
      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
      - PS_AMQP_BROKER
      - MHS_AMQP_BROKER
      - PS_QUEUE_NAME
      - MHS_QUEUE_NAME
      - PS_AMQP_USERNAME
      - PS_AMQP_PASSWORD
      - PS_AMQP_MAX_REDELIVERIES
      - MHS_AMQP_USERNAME
      - MHS_AMQP_PASSWORD
      - MHS_AMQP_MAX_REDELIVERIES
      - MHS_BASE_URL
      - PS_LOGGING_LEVEL
      - SUPPORTED_FILE_TYPES
      - STORAGE_TYPE
      - STORAGE_REGION
      - STORAGE_CONTAINER_NAME
      - STORAGE_REFERENCE
      - STORAGE_SECRET
    networks:
      - nia-ps

  ps_db:
    image: postgres:14.0
    ports:
      - "${PS_DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD
      - PS_DB_OWNER_NAME
    networks:
      - nia-ps

  db_migration:
    image: nhsdev/nia-ps-db-migration:0.2
    depends_on:
      - ps_db
    environment:
      - POSTGRES_PASSWORD
      - PS_DB_OWNER_NAME
      - PS_DB_URL
      - GPC_FACADE_USER_DB_PASSWORD
      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
    networks:
      - nia-ps

  ########### LOCAL TESTING ONLY #################

  dynamodb:
    image: nhsdev/nia-dynamodb-local:1.0.3
    networks:
      - nia-ps
    ports:
      - "8000:8000"

  redis:
    image: redis
    networks:
      - nia-ps
    ports:
      - "6379:6379"

  activemq:
    build:
      context: docker/activemq
    ports:
      - "8161:8161"
      - "${ACTIVE_MQ_PORT}:5672"
    networks:
      - nia-ps

  mock-spine-mhs:
    build:
      context: ./
      dockerfile: docker/mock-spine-mhs-outbound/DockerFile
    ports:
      - "${MOCK_SPINE_MHS_PORT}:8086"
      - "${MOCK_SPINE_MHS_FORWARD_RELIABLE_PORT}:8443"
    depends_on:
      - ps_db
    environment:
      - PS_DB_URL
      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
      - MOCK_SPINE_MHS_OUTBOUND_LOG_LEVEL
    networks:
      - nia-ps