version: '3.8'
services:
  gpc_facade:
    build:
      context: ../
      dockerfile: ./docker/gpc-facade/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GPC_FACADE_SERVER_PORT
      - PS_DB_URL=jdbc:postgresql://ps_db:5432
      - GPC_FACADE_USER_DB_PASSWORD
      - PS_AMQP_BROKER=amqp://activemq:5672
      - PS_QUEUE_NAME
      - PS_AMQP_USERNAME
      - PS_AMQP_PASSWORD
      - PS_AMQP_MAX_REDELIVERIES
      - PS_LOGGING_LEVEL
    networks:
      - ps-network

  gp2gp_translator:
    build:
      context: ../
      dockerfile: ./docker/gp2gp-translator/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - GP2GP_TRANSLATOR_SERVER_PORT
      - PS_DB_URL=jdbc:postgresql://ps_db:5432
      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
      - PS_AMQP_BROKER=amqp://activemq:5672
      - MHS_AMQP_BROKER=amqp://activemq:5672
      - PS_QUEUE_NAME
      - MHS_QUEUE_NAME
      - PS_AMQP_USERNAME
      - PS_AMQP_PASSWORD
      - PS_AMQP_MAX_REDELIVERIES
      - MHS_AMQP_USERNAME
      - MHS_AMQP_PASSWORD
      - MHS_AMQP_MAX_REDELIVERIES
      - MHS_BASE_URL=http://mhs-adaptor-mock:8080/
      - PS_LOGGING_LEVEL
    networks:
      - ps-network

  ps_db:
    build: ./db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD
      - PS_DB_OWNER_NAME
      - PS_DB_OWNER_PASSWORD
    networks:
      - ps-network

  db_migration:
    build:
      context: ../
      dockerfile: ./docker/db-migration/Dockerfile
    environment:
      - POSTGRES_PASSWORD
      - PS_DB_OWNER_NAME
      - PS_DB_OWNER_PASSWORD
      - PS_DB_URL
      - GPC_FACADE_USER_DB_PASSWORD
      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
    networks:
      - ps-network

  mhs-adaptor-mock:
    build: ./mhs-adaptor-mock
    ports:
      - "8080:8080"
    networks:
      - ps-network

  activemq:
    build: ./activemq
    ports:
      - "5672:5672"
      - "8161:8161"
    networks:
      - ps-network

networks:
  ps-network:
    external: true
