version: '3.8'
services:
  gpc_facade:
    build:
      context: ../
      dockerfile: ./docker/gpc-facade/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GPC_SERVER_PORT
      - PS_DB_DOCKER_URL=jdbc:postgresql://172.17.0.1:5436/patient_switching
      - GPC_USER_DB_PASSWORD
      - PSS_AMQP_BROKER=amqp://activemq:5672
      - PSS_QUEUE_NAME
      - PSS_AMQP_USERNAME
      - PSS_AMQP_PASSWORD
      - PSS_AMQP_MAX_REDELIVERIES

  gp2gp_translator:
    build:
      context: ../
      dockerfile: ./docker/gp2gp-translator/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - GP2GP_SERVER_PORT
      - PS_DB_DOCKER_URL=jdbc:postgresql://172.17.0.1:5436/patient_switching
      - GP2GP_USER_DB_PASSWORD
      - PSS_AMQP_BROKER=amqp://activemq:5672
      - MHS_AMQP_BROKER=amqp://activemq:5672
      - PSS_QUEUE_NAME
      - MHS_QUEUE_NAME
      - PSS_AMQP_USERNAME
      - PSS_AMQP_PASSWORD
      - PSS_AMQP_MAX_REDELIVERIES
      - MHS_AMQP_USERNAME
      - MHS_AMQP_PASSWORD
      - MHS_AMQP_MAX_REDELIVERIES

  pss_db:
    build: ./db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD
      - PS_DB_OWNER_NAME
      - PS_DB_OWNER_PASSWORD

  mhs-adaptor-mock:
    build: ./mhs-adaptor-mock
    ports:
      - "8080:8080"

  activemq:
    build: ./activemq
    ports:
      - "5672:5672"
      - "8161:8161"