version: '3.8'
services:
  gpc_facade:
    container_name: gpc_facade_tests
    build:
      target: build
    entrypoint: "gradle test"
    environment:
      - GPC_FACADE_SERVER_PORT
      - PSS_DB_URL
      - GPC_FACADE_USER_DB_PASSWORD

  gp2gp_translator:
    container_name: gp2gp_translator_tests
    build:
      target: build
    entrypoint: "gradle test"
    environment:
      - GP2GP_TRANSLATOR_SERVER_PORT
      - PSS_DB_URL
      - GP2GP_TRANSLATOR_USER_DB_PASSWORD
      - PSS_DB_OWNER_NAME
      - PSS_DB_OWNER_PASSWORD
