server:
  port: ${GP2GP_TRANSLATOR_SERVER_PORT:8085}

logging:
  level:
    uk.nhs.adaptors.pss.translator: DEBUG

spring:
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5436/patient_switching}
    username: gp2gp_user
    password: ${GP2GP_TRANSLATOR_USER_DB_PASSWORD}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics