server:
  port: ${GP2GP_SERVER_PORT:8085}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings
