version: '3'

networks:
  default:
    name: nia-ps
    external: true

services:
  nf-test-2:
    environment:
      - FACADE_URL=$FACADE_URL
      - FACADE_PORT=$FACADE_PORT
      - INBOUND_URL=$INBOUND_URL
      - INBOUND_PORT=$INBOUND_PORT
    build: .
    networks:
      - default