name: GP2GP Sending Adaptor Build Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  common-modules-tests:
    name: "Common Modules Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Common Modules Tests
        working-directory: ./docker
        run: |
          docker network create ps-network || true
          docker compose -f ./docker-compose.yml -f ./docker-compose-checks.yml build common_modules
          docker compose -f ./docker-compose.yml -f ./docker-compose-checks.yml up \
           --exit-code-from common_modules common_modules
          docker cp common_modules_checks:/home/gradle/service/db-connector/build db-connector-build
          docker cp common_modules_checks:/home/gradle/service/common/build common-build

  facade-tests:
    name: "GPC API Facade Tests"
    uses: ./.github/workflows/test_workflow.yml
    with:
      name: GPC API Facade
      path: ./gpc-api-facade
    secrets: inherit

  translator-tests:
    name: "GP2GP Translator Tests"
    uses: ./.github/workflows/test_workflow.yml
    with:
      name: GP2GP Translator
      path: ./gp2gp-translator
    secrets: inherit

  publish-docker-images:
    name: "Build and publish docker images to ECR"
    runs-on: ubuntu-latest
    needs: [ common-modules-tests, facade-tests, translator-tests ]
    steps:
      - name: Build Docker Images
        run: echo "TODO"

