name: GP2GP Sending Adaptor Build Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  facade-tests:
    uses: ./.github/workflows/test_workflow.yml
    with:
      name: GPC API Facade
      path: ./gpc-api-facade
    secrets: inherit

  translator-tests:
    uses: ./.github/workflows/test_workflow.yml
    with:
      name: GP2GP Translator
      path: ./gp2gp-translator
    secrets: inherit
