name: "Mutation Testing Workflow"
on:
  pull_request:

jobs:
  gp2gp-translator-mutation-testing:
    name: "Mutation Testing"
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        path: [ ./gpc-api-facade, ./gp2gp-translator]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 2
      - name: Setup Java JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: run pitest
        working-directory: ${{ matrix.path }}
        run: ./gradlew pitest-github
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}