name: "Mutation Testing Workflow"
on:
  pull_request:

jobs:
  gp2gp-translator-mutation-testing:
    name: "Mutation Testing"
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        path: [ ./gpc-api-facade, ./gp2gp-translator]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 2
      - name: Setup Java JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          distribution: 'temurin'
          java-version: 21

      - name: run pitest
        working-directory: ${{ matrix.path }}
        run: ./gradlew pitest-github
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}