on:
  release:
    types: [published]

jobs:
  push_to_dockerhub:
    strategy:
      matrix:
        config:
          - folder: docker/gp2gp-translator
            dockerhub_name: nia-ps-adaptor
          - folder: docker/gpc-facade
            dockerhub_name: nia-ps-facade
          - folder: docker/db-migration
            dockerhub_name: nia-ps-db-migration
          - folder: docker/snomed-schema
            dockerhub_name: nia-ps-snomed-schema

    uses: NHSDigital/integration-adaptor-actions/.github/workflows/release-adaptor-container-image.yml@main
    with:
      folder: ${{ matrix.config.folder }}
      dockerhub_name: ${{ matrix.config.dockerhub_name }}
      upload_url: ${{ github.event.release.upload_url }}
    secrets: inherit