on:
  push:
    tags: "*"

jobs:
  push_to_dockerhub:
    strategy:
      matrix:
        image:
          - {folder: gp2gp-translator, dockerhub_name: nia-ps-adaptor}
          - {folder: gpc-facade, dockerhub_name: nia-ps-facade}
          - {folder: db-migration, dockerhub_name: nia-ps-db-migration}
          - {folder: snomed-schema, dockerhub_name: nia-ps-snomed-schema}
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            nhsdev/${{ matrix.image.dockerhub_name }}
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/docker/${{ matrix.image.folder }}/Dockerfile
      - name: Log in to the Container registry
        uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          file: docker/${{ matrix.image.folder }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8,linux/amd64